package com.github.hosseinzafari.touristo.base.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFE7B171)
val md_theme_light_onPrimary = Color(0xFFFDE8D0)
val md_theme_light_primaryContainer = Color(0xFFFFDDB8)
val md_theme_light_onPrimaryContainer = Color(0xFF2B1700)
val md_theme_light_secondary = Color(0xFF1B3232)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF6FF7F7)
val md_theme_light_onSecondaryContainer = Color(0xFF002020)
val md_theme_light_tertiary = Color(0xFF835400)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB5)
val md_theme_light_onTertiaryContainer = Color(0xFF2A1800)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF2A1800)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF2A1800)
val md_theme_light_surfaceVariant = Color(0xFFF1E0D0)
val md_theme_light_onSurfaceVariant = Color(0xFF504539)
val md_theme_light_outline = Color(0xFF827568)
val md_theme_light_inverseOnSurface = Color(0xFFFFEEDE)
val md_theme_light_inverseSurface = Color(0xFF462A00)
val md_theme_light_inversePrimary = Color(0xFFFFB961)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF865300)
val md_theme_light_outlineVariant = Color(0xFFD4C4B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB961)
val md_theme_dark_onPrimary = Color(0xFF472A00)
val md_theme_dark_primaryContainer = Color(0xFF663E00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB8)
val md_theme_dark_secondary = Color(0xFF4CDADB)
val md_theme_dark_onSecondary = Color(0xFF003737)
val md_theme_dark_secondaryContainer = Color(0xFF004F50)
val md_theme_dark_onSecondaryContainer = Color(0xFF6FF7F7)
val md_theme_dark_tertiary = Color(0xFFFFB957)
val md_theme_dark_onTertiary = Color(0xFF462B00)
val md_theme_dark_tertiaryContainer = Color(0xFF643F00)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF2A1800)
val md_theme_dark_onBackground = Color(0xFFFFDDB6)
val md_theme_dark_surface = Color(0xFF2A1800)
val md_theme_dark_onSurface = Color(0xFFFFDDB6)
val md_theme_dark_surfaceVariant = Color(0xFF504539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C4B5)
val md_theme_dark_outline = Color(0xFF9C8E81)
val md_theme_dark_inverseOnSurface = Color(0xFF2A1800)
val md_theme_dark_inverseSurface = Color(0xFFFFDDB6)
val md_theme_dark_inversePrimary = Color(0xFF865300)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB961)
val md_theme_dark_outlineVariant = Color(0xFF504539)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFE7B171)
val CustomColor1 = Color(0xFFE7B171)
val light_CustomColor1 = Color(0xFF865300)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFFFDDB8)
val light_onCustomColor1Container = Color(0xFF2B1700)
val dark_CustomColor1 = Color(0xFFFFB961)
val dark_onCustomColor1 = Color(0xFF472A00)
val dark_CustomColor1Container = Color(0xFF663E00)
val dark_onCustomColor1Container = Color(0xFFFFDDB8)

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val MilkColor = Color(0xFFFDE8D0)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)